/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.*/

class Solution {
public:
		char findTheDifference(string s, string t) {
				int arr[26]={0};
				for(auto i:s)
						arr[(int(i)-97)]++;
							for(auto i:t){
									if(arr[(int(i)-97)]==0)
											return i;
						arr[(int(i)-97)]--;
							}
				return 'y';
		}
		
};